name: "CI Pipeline"
on:
  pull_request_target:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true # cancel existing runs if PR has been updated -- cost savings

jobs:
  ci_pipeline:
    name: "CI Pipeline"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node JS
        uses: actions/setup-node@v4
        with:
          node-version-file: "./.nvmrc"
      - name: Install Dependencies
        run: npm install
      - name: Build for production
        run: npm run build
